<UI>:
    MDBoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "hello kivyMD"
            font_style: 'Subtitle1'
            halign: 'center'
            #color: "#FF33FF"
            theme_text_color: 'Custom'
            text_color: 0, 0, 1, 1
        MDIcon:
            icon: "key"
            pos_hint: {"center_x": .5, "center_y": .5}
            color: "#CC00FF"
